### ISSUE TITLE
Does not work on Windows Vista

### ISSUE THREAD

**Issue by samumt** [javierbrea/contact-sensor-domapic-module#2]
I'm trying to install on Windows Vista OS and It does not work, please we need support

**Comment by javierbrea** [comment]
Hello @samumt (AKA Samu), first of all, thank you for your feedback. 
Congratulations for achieving to run Windows Vista on a Raspberry PI, and make GPIOs work. Some day you'll have to explain me how... and over all, WHY. 😜

Please provide all logs to know more about the error you have received when installing the package... or you can also simply close the issue 😉

**Comment by samumt** [comment]
jajaja thanks

**Comment by javierbrea** [comment]
I proceed to delete the issue as it was clearly a joke.
